### ISSUE TITLE
plugin is causing site to go down 

### ISSUE THREAD

**Issue by basicabe** [hps/heartland-woocommerce-plugin#94]
Hello, 

I'm using the Heartland woocommerce Secure Submit plugin and the site has crashed. we determined that the plugin was the problem. Do you know of any conflicts ? have you been getting any other inquiries why the plug in crashes the site? 

thanks for your response! 

David Abrahamian

**Comment by slogsdon** [comment]
Hi @basicabe! Apologies for the delay.

This is most likely due to an issue we discovered with older versions of PHP. We've issued a fix as #93, which you can install with this ZIP archive: https://github.com/hps/heartland-woocommerce-plugin/archive/fix-context-error.zip. We're looking to get this fix released to WordPress Plugin Directory this week.

**Comment by basicabe** [comment]
thank you! that worked.

**Comment by slogsdon** [comment]
@basicabe Thanks for the follow up! Please let us know if you experience any issues moving forward.
